---
title: Spectral
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: "Another fine responsive  \nsite template freebie  \ncrafted by [HTML5
  UP](http://html5up.net)\n"
owner: Your Name
first_published: 2016
email: your-email@domain.com
baseurl: ''
url: http://yourdomain.com
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
markdown: kramdown
